#!/bin/sh
set -e

. /usr/share/debconf/confmodule

# APT::Get::Assume-Yes
echo "\$1 = $1"
echo "\$2 = $2"
echo "\$3 = $3"
echo "\$4 = $4"
echo "\$5 = $5"
echo "\$6 = $6"
echo "\$7 = $7"
echo "APT::Get::Assume-Yes = ${Assume-Yes}"
printenv


displayEULA(){
	echo ' Sample EULA Template'
	echo ' End-User License Agreement \("Agreement"\)'
	echo ' Our EULA was last updated on 08\/07\/2023'
	echo ' Please read this End-User License Agreement carefully before Accpeting, downloading or'
	echo ' using DASH CLI 5.0.'
	echo ' Interpretation and Definitions'
	echo ' Interpretation'
	echo ' The words of which the initial letter is capitalized have meanings defined under the following conditions.'
	echo ' The following definitions shall have the same meaning regardless of whether they appear in singular or in'
	echo 'Enter Y to agree and accept'
	echo 'Do you Accept?(Y)es/(N)o.'

	read choice
	echo "choice = ${choice}"
	if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
		echo "INstallation Started ..."
		exit 0
	else #[ "$choice" = "N" ] || [ "$choice" = 'n' ]; then
		echo "INSTALLATION ABORTED XXX"
		exit -1
	fi
}
echo "Do you want to read License Terms? (Y)es/(N)o"
read choice
echo "choice = ${choice}"
if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
	displayEULA
	exit 0
else #[ "$choice" = "N" ] || [ "$choice" = 'n' ]; then
	echo "INSTALLATION ABORTED XXX"
	exit -1
fi
